version: '3.8'

services:
  
  banco_pitchpulse:
    image: postgres:15
    container_name: container_banco_pitchpulse
    environment:
      POSTGRES_DB: meu_banco
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha_secreta
    ports:
      - "5433:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - dados_postgres:/var/lib/postgresql/data
    networks:
      - rede_pitchpulse

  
  api_fastapi:
    build: .
    container_name: container_api_pitchpulse
    command: uvicorn app.api:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
    depends_on:
      - banco_pitchpulse
    networks:
      - rede_pitchpulse


  scraper_futebol:
    build: .
    container_name: container_scraper_pitchpulse
    command: python app/scraper.py
    volumes:
      - .:/code
    environment:
      PYTHONUNBUFFERED: "1"
    depends_on:
      - banco_pitchpulse
    networks:
      - rede_pitchpulse

networks:
  rede_pitchpulse:
    driver: bridge

volumes:
  dados_postgres: