services:
  banco_pitchpulse:
    image: postgres:15
    container_name: container_banco_pitchpulse
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: placar_futebol
    ports:
      - "5432:5432"
    volumes:
      - pitchpulseapi_dados_postgres:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d placar_futebol"]
      interval: 3s
      timeout: 3s
      retries: 5
    networks:
      - rede_pitchpulse

  api_fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: container_api_pitchpulse
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    environment:
      - DB_HOST=banco_pitchpulse
      - DB_USER=postgres
      - DB_PASSWORD=postgres_password
      - DB_NAME=placar_futebol
      - PYTHONPATH=/code
    depends_on:
      banco_pitchpulse:
        condition: service_healthy
    working_dir: /code
    command: uvicorn backend.api:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - rede_pitchpulse

  scraper_futebol:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: container_scraper_pitchpulse
    volumes:
      - .:/code
    environment:
      - DATABASE_URL=postgresql://postgres:postgres_password@banco_pitchpulse:5432/placar_futebol
      - DB_HOST=banco_pitchpulse
      - DB_USER=postgres
      - DB_PASSWORD=postgres_password
      - DB_NAME=placar_futebol
      - PYTHONPATH=/code
    depends_on:
      banco_pitchpulse:
        condition: service_healthy
    working_dir: /code
    command: python backend/scraper.py 
    networks:
      - rede_pitchpulse

volumes:
  pitchpulseapi_dados_postgres:

networks:
  rede_pitchpulse:
    driver: bridge