name: Atualizar Dados da Copa (Scraper)

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch: {}

jobs:
  rodar-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar o Scraper (uma única vez)
        working-directory: backend
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SCRAPER_LOOP_CONTINUO: "false"
        run: python scraper.py
